main = ".open-next/worker.js"
name = "la-tortugueta"
compatibility_date = "2025-03-25"
compatibility_flags = [ "nodejs_compat" ]

[vars]
NEXT_PUBLIC_R2_PUBLIC_URL = "https://pub-6d7cc19d77b44520a5ac19e77cb47c4e.r2.dev"
NEXTAUTH_URL = "https://la-tortugueta.bor-arroyo.workers.dev"
NEXT_PUBLIC_SUPABASE_URL = "https://fjnseqtjtuciimwpycrh.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqbnNlcXRqdHVjaWltd3B5Y3JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3MDcyOTEsImV4cCI6MjA3ODI4MzI5MX0.QE-4zZdLUFjvLLKmaFnOEtXb4QOjFjHyaaDUXMNq-Sk"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqbnNlcXRqdHVjaWltd3B5Y3JoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MjcwNzI5MSwiZXhwI220NzgzMjkyOX0.ysRN3b7g54xTTvN8ngI-fdnnyqQQWujp6POhtIwqURw"
NEXTAUTH_SECRET = "9b6a34f81a63d94f6c59a8b7d7a1f0e3b04f3d7c218a56d2c3f87a1269db41e1"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Bucket R2 para cach√© de Next.js
[[r2_buckets]]
binding = "CACHE_BUCKET"
bucket_name = "latortugueta-cache"
